// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoadBalancer.proto

#include "LoadBalancer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace hbase {
namespace pb {
class LoadBalancerStateDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LoadBalancerState> _instance;
} _LoadBalancerState_default_instance_;
}  // namespace pb
}  // namespace hbase
static void InitDefaultsscc_info_LoadBalancerState_LoadBalancer_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hbase::pb::_LoadBalancerState_default_instance_;
    new (ptr) ::hbase::pb::LoadBalancerState();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hbase::pb::LoadBalancerState::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LoadBalancerState_LoadBalancer_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_LoadBalancerState_LoadBalancer_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_LoadBalancer_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_LoadBalancer_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_LoadBalancer_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_LoadBalancer_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::hbase::pb::LoadBalancerState, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::hbase::pb::LoadBalancerState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hbase::pb::LoadBalancerState, balancer_on_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::hbase::pb::LoadBalancerState)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::hbase::pb::_LoadBalancerState_default_instance_),
};

const char descriptor_table_protodef_LoadBalancer_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022LoadBalancer.proto\022\010hbase.pb\"(\n\021LoadBa"
  "lancerState\022\023\n\013balancer_on\030\001 \001(\010BE\n*org."
  "apache.hadoop.hbase.protobuf.generatedB\022"
  "LoadBalancerProtosH\001\240\001\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_LoadBalancer_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_LoadBalancer_2eproto_sccs[1] = {
  &scc_info_LoadBalancerState_LoadBalancer_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_LoadBalancer_2eproto_once;
static bool descriptor_table_LoadBalancer_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_LoadBalancer_2eproto = {
  &descriptor_table_LoadBalancer_2eproto_initialized, descriptor_table_protodef_LoadBalancer_2eproto, "LoadBalancer.proto", 143,
  &descriptor_table_LoadBalancer_2eproto_once, descriptor_table_LoadBalancer_2eproto_sccs, descriptor_table_LoadBalancer_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_LoadBalancer_2eproto::offsets,
  file_level_metadata_LoadBalancer_2eproto, 1, file_level_enum_descriptors_LoadBalancer_2eproto, file_level_service_descriptors_LoadBalancer_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_LoadBalancer_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_LoadBalancer_2eproto), true);
namespace hbase {
namespace pb {

// ===================================================================

void LoadBalancerState::InitAsDefaultInstance() {
}
class LoadBalancerState::_Internal {
 public:
  using HasBits = decltype(std::declval<LoadBalancerState>()._has_bits_);
  static void set_has_balancer_on(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

LoadBalancerState::LoadBalancerState()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hbase.pb.LoadBalancerState)
}
LoadBalancerState::LoadBalancerState(const LoadBalancerState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  balancer_on_ = from.balancer_on_;
  // @@protoc_insertion_point(copy_constructor:hbase.pb.LoadBalancerState)
}

void LoadBalancerState::SharedCtor() {
  balancer_on_ = false;
}

LoadBalancerState::~LoadBalancerState() {
  // @@protoc_insertion_point(destructor:hbase.pb.LoadBalancerState)
  SharedDtor();
}

void LoadBalancerState::SharedDtor() {
}

void LoadBalancerState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LoadBalancerState& LoadBalancerState::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LoadBalancerState_LoadBalancer_2eproto.base);
  return *internal_default_instance();
}


void LoadBalancerState::Clear() {
// @@protoc_insertion_point(message_clear_start:hbase.pb.LoadBalancerState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  balancer_on_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* LoadBalancerState::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional bool balancer_on = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_balancer_on(&has_bits);
          balancer_on_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool LoadBalancerState::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:hbase.pb.LoadBalancerState)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool balancer_on = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {
          _Internal::set_has_balancer_on(&_has_bits_);
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   bool, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL>(
                 input, &balancer_on_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hbase.pb.LoadBalancerState)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hbase.pb.LoadBalancerState)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void LoadBalancerState::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hbase.pb.LoadBalancerState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool balancer_on = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBool(1, this->balancer_on(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hbase.pb.LoadBalancerState)
}

::PROTOBUF_NAMESPACE_ID::uint8* LoadBalancerState::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hbase.pb.LoadBalancerState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool balancer_on = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->balancer_on(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hbase.pb.LoadBalancerState)
  return target;
}

size_t LoadBalancerState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hbase.pb.LoadBalancerState)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional bool balancer_on = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + 1;
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LoadBalancerState::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hbase.pb.LoadBalancerState)
  GOOGLE_DCHECK_NE(&from, this);
  const LoadBalancerState* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LoadBalancerState>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hbase.pb.LoadBalancerState)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hbase.pb.LoadBalancerState)
    MergeFrom(*source);
  }
}

void LoadBalancerState::MergeFrom(const LoadBalancerState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hbase.pb.LoadBalancerState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_balancer_on()) {
    set_balancer_on(from.balancer_on());
  }
}

void LoadBalancerState::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hbase.pb.LoadBalancerState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoadBalancerState::CopyFrom(const LoadBalancerState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hbase.pb.LoadBalancerState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoadBalancerState::IsInitialized() const {
  return true;
}

void LoadBalancerState::InternalSwap(LoadBalancerState* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(balancer_on_, other->balancer_on_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LoadBalancerState::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace hbase
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hbase::pb::LoadBalancerState* Arena::CreateMaybeMessage< ::hbase::pb::LoadBalancerState >(Arena* arena) {
  return Arena::CreateInternal< ::hbase::pb::LoadBalancerState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
